
server:
  port: 8080
  servlet:
    context-path: /



# ?????
spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      location: D:\tempory_download\大二下\实训\smart_meeting_system-main\smart_meeting_system-main
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/smart_meeting_system
      username: root
      password: "032205"
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms

logging:
  level:
    com.baomidou.mybatisplus.core: debug

# mybatis-plus???
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.homework.pojo
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted  #??????
      id-type: auto #???????

#jwt??
jwt:
  token:
    tokenExpiration: 120 #????,????
    tokenSignKey: headline123456  #???????? ???